/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  safelist: [
    'dark:bg-sky-500/10',
    'dark:border-sky-500/20',
    'dark:bg-sky-500/20',
    'dark:text-sky-400',
    'dark:bg-violet-500/10',
    'dark:border-violet-500/20',
    'dark:bg-violet-500/20',
    'dark:text-violet-400',
    'dark:bg-emerald-500/10',
    'dark:border-emerald-500/20',
    'dark:bg-emerald-500/20',
    'dark:text-emerald-400',
    'dark:bg-amber-500/10',
    'dark:border-amber-500/20',
    'dark:bg-amber-500/20',
    'dark:text-amber-400',
    'dark:bg-zinc-950',
    'dark:bg-zinc-900',
    'dark:bg-zinc-800',
    'dark:bg-zinc-700',
    'dark:text-zinc-100',
    'dark:text-zinc-300',
    'dark:text-zinc-400',
    'dark:text-zinc-500',
    'dark:text-zinc-600',
    'dark:border-zinc-700',
    'dark:border-zinc-800',
    'dark:shadow-indigo-950',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
